(DEFUN DEFUN () NIL)
(DEFUN LENISSUE ())
(DEFUN (PLUS 1 1) () ())

(DEFUN INVALIDPARAMS X (T))
(S1NOTLIST 1)

(DEFUN INVALIDBODY () (T))
(S2INVALIDFOREVAL)

(DEFUN INVALIDCALL1 (X) (PLUS X 1))
(PLUSPLUS X 1)

(DEFUN INVALIDCALL2 (X Y Z) (PLUS X (PLUS Y Z)))
(TRIPLEADD X Y)